### ISSUE TITLE
Scroll Option

### ISSUE THREAD

**Issue by hurrikimmen** [NotEnoughTina/FirstLady#3]
Hi! First, I love your FL bot and it works so well! I am pretty new to python and I was wondering if there was a way to add a scroll up once it clicks into the list? I noticed that when queues have more than 6 or 7 people waiting for approval it opens to the bottom of the list and it approves from the top of what it can see which aren't the people at the top of the list. Is there a way to add something in where after it clicks list it will do a scroll to the top of the list before it checks for the green check? Thank you so much for your work you have put into this, you are fantastic!

**Comment by NotEnoughTina** [comment]
Fixes this in the latest changes if you pull updates.
